### ISSUE TITLE
Isn't this code open source

### ISSUE THREAD

**Issue by kooKievovo** [KaiyuanZh/FLIP#1]
Isn't this code open source

**Comment by KaiyuanZh** [comment]
~~Hi, thanks for your attention! The code will be released soon.~~
Hi @kooKievovo, the code has been released.

**Comment by kooKievovo** [comment]
I have a question，FLIP need the benign models to adversarial training，so how to find the benign models before defense？Look forward to your answer and thank you.

**Comment by kooKievovo** [comment]
I have a question，FLIP need the benign models to adversarial training，so how to find the benign models before defense？Look forward to your answer and thank you.@KaiyuanZh

**Comment by 1imy** [comment]
AttributeError: module 'config' has no attribute 'AGGR_FOOLSGOLD'
I will be glad to see your code that is a completed version.

**Comment by KaiyuanZh** [comment]
Thank you for reaching out! As stated in Section 1 (Introduction: Threat Model), “On benign clients, we do not assume any knowledge about the ground truth trigger. Backdoor triggers are inverted on benign clients based on received model weights (from the global server) and their local data (non-i.i.d.).”

First, during training, each benign client can be considered as a defender. As benign clients do not want the global model to be poisoned, they will choose to participate in the defense. Second, benign clients have no knowledge about the trigger and they have no knowledge about which are malicious clients either. Benign clients follow the FL protocol, and they do not communicate with each other. In each round, benign clients invert triggers based on their local data and the received global model. Third, as mentioned in our paper, the global server has no knowledge about which client is malicious or benign.
