### ISSUE TITLE
code  doesn't work 

### ISSUE THREAD

**Issue by 1imy** [KaiyuanZh/FLIP#2]
AttributeError: module 'config' has no attribute 'AGGR_FOOLSGOLD'
I will be glad to see your code that is a completed version.

**Comment by KaiyuanZh** [comment]
Thank you for reaching out! As stated in the theoretical analysis section, our assumptions are based on the FedAvg protocol.

Aside from that, our framework is general and can be instantiated with different trigger inversion techniques. Your suggestion of examining other aggregation protocols is indeed interesting and could serve as a potential opportunity for future research!

In terms of the 'AGGR_FOOLSGOLD', all that's needed is to define a new configuration parameter in accordance with the `yaml` file and `config`, and it should works.

To put it more broadly, if you're interested in trying out different aggregation methods, you'll need to establish a new configuration parameter in the yaml file and incorporate your aggregation function. Once this is done, everything should function as expected.

**Comment by 1imy** [comment]
thank you a lot

Kaiyuan Zhang ***@***.***> 于2023年6月14日周三 02:46写道：

**Comment by 1imy** [comment]
when I change"AGGR_FOOLSGOLD" to "AGGR_MEAN", there will be some mistakes
like this:
[image: image.png]
in helper.py and weight_accumulator[name] is NoneType
and in helper.py the method def accumulate_weight

weight_accumulator  will be returned none when self.params[
"aggregation_methods"] == config.AGGR_MEAN:
and how can I sovle this bug.
I will be glad to hear from you!
mengyu li ***@***.***> 于2023年6月14日周三 10:05写道：
