### ISSUE TITLE
Ask for code help

### ISSUE THREAD

**Issue by LongJinhe-coder** [KaiyuanZh/FLIP#4]
Thank you for your article and code, which gave me a lot of help. I encountered difficulties during the experiment. I would like to ask if you can share with me the code to reproduce the previous defense method in the paper experiment, because my code I have limited abilities and can't do it myself, if you can help me, I will be very grateful！！

**Comment by KaiyuanZh** [comment]
Hi @LongJinhe-coder, thank you for reaching out and I'm glad to hear that our article and code have been helpful to your research.

Regarding your request for reproducing previous defense methods mentioned in our paper, I encourage you to refer to the original authors' GitHub repositories or the algorithms detailed in their papers. Best of luck with your experiments.
