### ISSUE TITLE
Code redundancy in the main.py file and aggregation model

### ISSUE THREAD

**Issue by mtuann** [KaiyuanZh/FLIP#5]
In the main.py file, lines 167–194, what is the purpose of the phrase "logger.inflogger.info("end test the returned updates").
What I found in this code is that their local model doesn't change because each agent_name_key only contains one element.
Should we remove these lines of code, or is this my misunderstanding?

Anw, I thought FedAvg aggregation models would be based on one number of samples trained in each client, but in your code, the weight is equal for all clients, = self.params["lr_para"] / self.params["no_models"]. Could you explain this?

**Comment by KaiyuanZh** [comment]
Hi @mtuann, 

1. Lines 167–194 of the main.py file is for testing purposes. You can choose to remove it or keep it, depending on your need for logging this information in your experiment.
2. Regarding the FedAvg aggregation method in our code, we are follwoing the exsiting work's setting as we mentiond in our paper, we follow single-shot setting in [1] and continuous setting in [2] to perform the attacks.

[1]. Bagdasaryan et al. (2020), "How to backdoor federated learning".
[2]. Xie et al. (2020), "DBA: Distributed Backdoor Attacks against Federated Learning".
